-- Migration: 005_seed_admin
-- Description: Seed default admin user (generated by scripts/seed-admin.mjs)
-- Run this in your Supabase SQL editor or apply migrations

INSERT INTO users (nama, email, password, is_admin)
VALUES (
  'Super Admin',
  'admin@jogjakos.com',
  '$2b$12$dVBxNpaop3KoC/RKGtmiV.MDEjkTx3V.tH4mK7203vTJNxWRywMte',
  TRUE
)
ON CONFLICT (email)
DO UPDATE SET
  is_admin = TRUE,
  password = EXCLUDED.password,
  updated_at = NOW();
