import bcrypt from "bcryptjs";
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
import path from "path";

// Load environment variables manually if not already loaded (e.g. running under bare Node instead of Bun)
if (!process.env.VITE_SUPABASE_URL) {
  try {
    const envPath = path.resolve(process.cwd(), ".env");
    if (fs.existsSync(envPath)) {
      const envContent = fs.readFileSync(envPath, "utf-8");
      for (const line of envContent.split("\n")) {
        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
          const key = match[1];
          let value = match[2] || "";
          if (value.startsWith('"') && value.endsWith('"')) {
            value = value.slice(1, -1);
          } else if (value.startsWith("'") && value.endsWith("'")) {
            value = value.slice(1, -1);
          }
          process.env[key] = value;
        }
      }
    }
  } catch (e) {
    console.warn("⚠️ Gagal membaca file .env:", e.message);
  }
}

// Parse CLI args --key=value
const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, ...v] = a.replace(/^--/, "").split("=");
    return [k, v.join("=")];
  }),
);

const email = args.email ?? "admin@jogjakos.com";
const password = args.password ?? "admin123";
const nama = args.nama ?? "Super Admin";

console.log("⏳ Generating bcrypt hash...");
const hash = await bcrypt.hash(password, 12);

const sql = `-- Admin seed (generated by scripts/seed-admin.mjs)
-- Run this in your Supabase SQL editor

INSERT INTO users (nama, email, password, is_admin)
VALUES (
  '${nama}',
  '${email}',
  '${hash}',
  TRUE
)
ON CONFLICT (email)
DO UPDATE SET
  is_admin = TRUE,
  password = EXCLUDED.password,
  updated_at = NOW();
`;

console.log("\n✅ Seed SQL:");
console.log("─".repeat(60));
console.log(sql);
console.log("─".repeat(60));
console.log(`\n📋 Admin credentials:`);
console.log(`   Nama    : ${nama}`);
console.log(`   Email   : ${email}`);
console.log(`   Password: ${password}`);
console.log(`\n⚠️  Ganti password setelah login pertama!`);

// Attempt automatic insert into Supabase using JS client
const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (supabaseUrl && supabaseAnonKey) {
  console.log("\n🔌 Menghubungkan langsung ke database Supabase...");
  const supabase = createClient(supabaseUrl, supabaseAnonKey);

  try {
    // Check if user already exists
    const { data: existingUser, error: fetchError } = await supabase
      .from("users")
      .select("uuid")
      .eq("email", email)
      .maybeSingle();

    if (fetchError) {
      console.error("❌ Gagal memeriksa user di database:", fetchError.message);
    } else if (existingUser) {
      console.log(
        `🔄 User dengan email ${email} ditemukan. Memperbarui ke admin dan mengupdate password...`,
      );
      const { error: updateError } = await supabase
        .from("users")
        .update({
          nama,
          password: hash,
          is_admin: true,
          updated_at: new Date().toISOString(),
        })
        .eq("email", email);

      if (updateError) {
        console.error("❌ Gagal memperbarui data user admin:", updateError.message);
      } else {
        console.log("🎉 BERHASIL: User admin berhasil diperbarui langsung di database!");
      }
    } else {
      console.log(`➕ Membuat user admin baru dengan email ${email}...`);
      const { error: insertError } = await supabase.from("users").insert({
        nama,
        email,
        password: hash,
        is_admin: true,
      });

      if (insertError) {
        console.error("❌ Gagal membuat user admin baru:", insertError.message);
      } else {
        console.log("🎉 BERHASIL: User admin baru berhasil ditambahkan langsung ke database!");
      }
    }
  } catch (err) {
    console.error("❌ Terjadi kesalahan saat melakukan query ke database:", err.message);
  }
} else {
  console.log("\n⚠️ VITE_SUPABASE_URL atau VITE_SUPABASE_ANON_KEY tidak ditemukan di .env.");
  console.log("Silakan jalankan query SQL di atas secara manual di Supabase SQL Editor.");
}
