/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as KosUuidRouteImport } from './routes/kos.$uuid'
import { Route as DashboardVerifikasiRouteImport } from './routes/dashboard/verifikasi'
import { Route as DashboardTambahKosRouteImport } from './routes/dashboard/tambah-kos'
import { Route as DashboardEditUuidRouteImport } from './routes/dashboard/edit.$uuid'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const KosUuidRoute = KosUuidRouteImport.update({
  id: '/kos/$uuid',
  path: '/kos/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerifikasiRoute = DashboardVerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTambahKosRoute = DashboardTambahKosRouteImport.update({
  id: '/tambah-kos',
  path: '/tambah-kos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditUuidRoute = DashboardEditUuidRouteImport.update({
  id: '/edit/$uuid',
  path: '/edit/$uuid',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/katalog': typeof KatalogRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/mitra': typeof MitraRoute
  '/survey': typeof SurveyRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard/tambah-kos': typeof DashboardTambahKosRoute
  '/dashboard/verifikasi': typeof DashboardVerifikasiRoute
  '/kos/$uuid': typeof KosUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$uuid': typeof DashboardEditUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/katalog': typeof KatalogRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/mitra': typeof MitraRoute
  '/survey': typeof SurveyRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard/tambah-kos': typeof DashboardTambahKosRoute
  '/dashboard/verifikasi': typeof DashboardVerifikasiRoute
  '/kos/$uuid': typeof KosUuidRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit/$uuid': typeof DashboardEditUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/katalog': typeof KatalogRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/mitra': typeof MitraRoute
  '/survey': typeof SurveyRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard/tambah-kos': typeof DashboardTambahKosRoute
  '/dashboard/verifikasi': typeof DashboardVerifikasiRoute
  '/kos/$uuid': typeof KosUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$uuid': typeof DashboardEditUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/daftar'
    | '/dashboard'
    | '/katalog'
    | '/login'
    | '/masuk'
    | '/mitra'
    | '/survey'
    | '/wishlist'
    | '/dashboard/tambah-kos'
    | '/dashboard/verifikasi'
    | '/kos/$uuid'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/edit/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/katalog'
    | '/login'
    | '/masuk'
    | '/mitra'
    | '/survey'
    | '/wishlist'
    | '/dashboard/tambah-kos'
    | '/dashboard/verifikasi'
    | '/kos/$uuid'
    | '/admin'
    | '/dashboard'
    | '/dashboard/edit/$uuid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/daftar'
    | '/dashboard'
    | '/katalog'
    | '/login'
    | '/masuk'
    | '/mitra'
    | '/survey'
    | '/wishlist'
    | '/dashboard/tambah-kos'
    | '/dashboard/verifikasi'
    | '/kos/$uuid'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/edit/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  KatalogRoute: typeof KatalogRoute
  LoginRoute: typeof LoginRoute
  MasukRoute: typeof MasukRoute
  MitraRoute: typeof MitraRoute
  SurveyRoute: typeof SurveyRoute
  WishlistRoute: typeof WishlistRoute
  KosUuidRoute: typeof KosUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kos/$uuid': {
      id: '/kos/$uuid'
      path: '/kos/$uuid'
      fullPath: '/kos/$uuid'
      preLoaderRoute: typeof KosUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verifikasi': {
      id: '/dashboard/verifikasi'
      path: '/verifikasi'
      fullPath: '/dashboard/verifikasi'
      preLoaderRoute: typeof DashboardVerifikasiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tambah-kos': {
      id: '/dashboard/tambah-kos'
      path: '/tambah-kos'
      fullPath: '/dashboard/tambah-kos'
      preLoaderRoute: typeof DashboardTambahKosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit/$uuid': {
      id: '/dashboard/edit/$uuid'
      path: '/edit/$uuid'
      fullPath: '/dashboard/edit/$uuid'
      preLoaderRoute: typeof DashboardEditUuidRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardTambahKosRoute: typeof DashboardTambahKosRoute
  DashboardVerifikasiRoute: typeof DashboardVerifikasiRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditUuidRoute: typeof DashboardEditUuidRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTambahKosRoute: DashboardTambahKosRoute,
  DashboardVerifikasiRoute: DashboardVerifikasiRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditUuidRoute: DashboardEditUuidRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DaftarRoute: DaftarRoute,
  DashboardRoute: DashboardRouteWithChildren,
  KatalogRoute: KatalogRoute,
  LoginRoute: LoginRoute,
  MasukRoute: MasukRoute,
  MitraRoute: MitraRoute,
  SurveyRoute: SurveyRoute,
  WishlistRoute: WishlistRoute,
  KosUuidRoute: KosUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
